import cover from "../assets/topCourses/top_course1.jpg";
import avater from "../assets/avater/avater1.jpg";

export const coursesData = [
  {
    id: "BLC001",
    title: "The Complete Python Bootcamp From Zero to Hero in Python",
    regulerPrice: 249,
    offerPrice: 74,
    coverImg: cover,
    author: "Jhon Mick",
    avater: avater,
    published: "24-04-2020",
    lastUpdate: "24-04-2023",
    enrolled: 2523,
    totalLession: 29,
    rating: 4.5,
    raatingCount: 45,
    duration: "12 hours",
    level: "All",
    courseOutline: [
      "Course overview",
      "Python setup",
      "Python object and data structure basics",
      "Python Comparison operators",
      "Pthon Statements",
      "Quiz 1",
      "Methods and functions",
      "Milestone project -1",
      "Object oriented programming",
      "Modules and packages",
      "Quiz 2",
    ],
  },
  {
    id: "BLC002",
    title: "The Complete 2023 Web Development Bootcamp",
    reulerPrice: 249,
    offerPrice: 74,
    coverImg: cover,
    author: "Jhon Mick",
    avater: avater,
    published: "24-04-2020",
    lastUpdate: "24-04-2023",
    enrolled: 2523,
    totalLession: 29,
    rating: 4.5,
    raatingCount: 45,
    duration: "12 hours",
    level: "All",
    courseOutline: [
      "Front-End Web Development",
      "Introduction to HTML",
      "Intermediate HTML",
      "Quiz 1",
      "Multi-Page Websites",
      "Introduction to CSS",
      "CSS Properties",
      "Quiz 2",
      "Intermediate CSS",
      "Advanced CSS",
      "Project -1",
    ],
  },
  {
    id: "BLC003",
    title: "The Complete JavaScript Course 2023: From Zero to Expert!",
    regulerPrice: 369,
    offerPrice: 99,
    coverImg: cover,
    author: "Jhon Mick",
    avater: avater,
    published: "24-04-2020",
    lastUpdate: "24-04-2023",
    enrolled: 2523,
    totalLession: 29,
    rating: 4.5,
    raatingCount: 45,
    duration: "12 hours",
    level: "All",
    courseOutline: [
      "Welcome, Welcome, Welcome!",
      "JavaScript Fundamentals – Part 1",
      "Quiz 1",
      "JavaScript Fundamentals – Part 2",
      "Quiz 2",
      "How to Navigate This Course",
      "Developer Skills & Editor Setup",
      "[OPTIONAL] HTML & CSS Crash Course",
      "JavaScript in the Browser: DOM and Events Fundamentals",
      "How JavaScript Works Behind the Scenes",
      "Data Structures, Modern Operators and Strings",
    ],
  },
  {
    id: "BLC004",
    title: "Complete Data Structure and Algorithm with Javascript",
    price: 499,
    coverImg: cover,
    author: "Jhon Mick",
    avater: avater,
    published: "24-04-2020",
    lastUpdate: "24-04-2023",
    enrolled: 2523,
    totalLession: 29,
    rating: 4.5,
    raatingCount: 45,
    duration: "12 hours",
    level: "All",
    courseOutline: [
      "Introduction to Javascript",
      "Variable in Javascript",
      "Data types in Javascript",
      "Operators in Javascript",
      "Conditions in Javascript",
      "Quiz 1",
      "Loop in C",
      "Simple calculator with Javascript",
      "Grade calculation with Javascript",
      "Functions in Javascript",
      "Quiz 2",
    ],
  },
  {
    id: "BLC005",
    title: "The Complete Python Bootcamp From Zero to Hero in Python",
    regulerPrice: 249,
    offerPrice: 74,
    coverImg: cover,
    author: "Jhon Mick",
    avater: avater,
    published: "24-04-2020",
    lastUpdate: "24-04-2023",
    enrolled: 2523,
    totalLession: 29,
    rating: 4.5,
    raatingCount: 45,
    duration: "12 hours",
    level: "All",
    courseOutline: [
      "Course overview",
      "Python setup",
      "Python object and data structure basics",
      "Python Comparison operators",
      "Pthon Statements",
      "Quiz 1",
      "Methods and functions",
      "Milestone project -1",
      "Object oriented programming",
      "Modules and packages",
      "Quiz 2",
    ],
  },
  {
    id: "BLC006",
    title: "The Complete 2023 Web Development Bootcamp",
    reulerPrice: 249,
    offerPrice: 74,
    coverImg: cover,
    author: "Jhon Mick",
    avater: avater,
    published: "24-04-2020",
    lastUpdate: "24-04-2023",
    enrolled: 2523,
    totalLession: 29,
    rating: 4.5,
    raatingCount: 45,
    duration: "12 hours",
    level: "All",
    courseOutline: [
      "Front-End Web Development",
      "Introduction to HTML",
      "Intermediate HTML",
      "Quiz 1",
      "Multi-Page Websites",
      "Introduction to CSS",
      "CSS Properties",
      "Quiz 2",
      "Intermediate CSS",
      "Advanced CSS",
      "Project -1",
    ],
  },
  {
    id: "BLC007",
    title: "The Complete JavaScript Course 2023: From Zero to Expert!",
    regulerPrice: 369,
    offerPrice: 99,
    coverImg: cover,
    author: "Jhon Mick",
    avater: avater,
    published: "24-04-2020",
    lastUpdate: "24-04-2023",
    enrolled: 2523,
    totalLession: 29,
    rating: 4.5,
    raatingCount: 45,
    duration: "12 hours",
    level: "All",
    courseOutline: [
      "Welcome, Welcome, Welcome!",
      "JavaScript Fundamentals – Part 1",
      "Quiz 1",
      "JavaScript Fundamentals – Part 2",
      "Quiz 2",
      "How to Navigate This Course",
      "Developer Skills & Editor Setup",
      "[OPTIONAL] HTML & CSS Crash Course",
      "JavaScript in the Browser: DOM and Events Fundamentals",
      "How JavaScript Works Behind the Scenes",
      "Data Structures, Modern Operators and Strings",
    ],
  },
  {
    id: "BLC008",
    title: "Complete Data Structure and Algorithm with Javascript",
    price: 499,
    coverImg: cover,
    author: "Jhon Mick",
    avater: avater,
    published: "24-04-2020",
    lastUpdate: "24-04-2023",
    enrolled: 2523,
    totalLession: 29,
    rating: 4.5,
    raatingCount: 45,
    duration: "12 hours",
    level: "All",
    courseOutline: [
      "Introduction to Javascript",
      "Variable in Javascript",
      "Data types in Javascript",
      "Operators in Javascript",
      "Conditions in Javascript",
      "Quiz 1",
      "Loop in C",
      "Simple calculator with Javascript",
      "Grade calculation with Javascript",
      "Functions in Javascript",
      "Quiz 2",
    ],
  },
  {
    id: "BLC009",
    title: "The Complete Python Bootcamp From Zero to Hero in Python",
    regulerPrice: 249,
    offerPrice: 74,
    coverImg: cover,
    author: "Jhon Mick",
    avater: avater,
    published: "24-04-2020",
    lastUpdate: "24-04-2023",
    enrolled: 2523,
    totalLession: 29,
    rating: 4.5,
    raatingCount: 45,
    duration: "12 hours",
    level: "All",
    courseOutline: [
      "Course overview",
      "Python setup",
      "Python object and data structure basics",
      "Python Comparison operators",
      "Pthon Statements",
      "Quiz 1",
      "Methods and functions",
      "Milestone project -1",
      "Object oriented programming",
      "Modules and packages",
      "Quiz 2",
    ],
  },
  {
    id: "BLC0010",
    title: "The Complete 2023 Web Development Bootcamp",
    reulerPrice: 249,
    offerPrice: 74,
    coverImg: cover,
    author: "Jhon Mick",
    avater: avater,
    published: "24-04-2020",
    lastUpdate: "24-04-2023",
    enrolled: 2523,
    totalLession: 29,
    rating: 4.5,
    raatingCount: 45,
    duration: "12 hours",
    level: "All",
    courseOutline: [
      "Front-End Web Development",
      "Introduction to HTML",
      "Intermediate HTML",
      "Quiz 1",
      "Multi-Page Websites",
      "Introduction to CSS",
      "CSS Properties",
      "Quiz 2",
      "Intermediate CSS",
      "Advanced CSS",
      "Project -1",
    ],
  },
  {
    id: "BLC0011",
    title: "The Complete JavaScript Course 2023: From Zero to Expert!",
    regulerPrice: 369,
    offerPrice: 99,
    coverImg: cover,
    author: "Jhon Mick",
    avater: avater,
    published: "24-04-2020",
    lastUpdate: "24-04-2023",
    enrolled: 2523,
    totalLession: 29,
    rating: 4.5,
    raatingCount: 45,
    duration: "12 hours",
    level: "All",
    courseOutline: [
      "Welcome, Welcome, Welcome!",
      "JavaScript Fundamentals – Part 1",
      "Quiz 1",
      "JavaScript Fundamentals – Part 2",
      "Quiz 2",
      "How to Navigate This Course",
      "Developer Skills & Editor Setup",
      "[OPTIONAL] HTML & CSS Crash Course",
      "JavaScript in the Browser: DOM and Events Fundamentals",
      "How JavaScript Works Behind the Scenes",
      "Data Structures, Modern Operators and Strings",
    ],
  },
  {
    id: "BLC0012",
    title: "Complete Data Structure and Algorithm with Javascript",
    price: 499,
    coverImg: cover,
    author: "Jhon Mick",
    avater: avater,
    published: "24-04-2020",
    lastUpdate: "24-04-2023",
    enrolled: 2523,
    totalLession: 29,
    rating: 4.5,
    raatingCount: 45,
    duration: "12 hours",
    level: "All",
    courseOutline: [
      "Introduction to Javascript",
      "Variable in Javascript",
      "Data types in Javascript",
      "Operators in Javascript",
      "Conditions in Javascript",
      "Quiz 1",
      "Loop in C",
      "Simple calculator with Javascript",
      "Grade calculation with Javascript",
      "Functions in Javascript",
      "Quiz 2",
    ],
  },
];
